import type { FastifyReply } from 'fastify';
import type { MediaAlbumLink } from '@prisma/client';
import { prisma } from '../../db.js';
import {
  MediaProviderError,
  mediaErrorKey,
  mediaErrorStatus,
  type MediaProvider,
  type MediaAssetVariant,
  type MediaAssetSummary,
} from './registry.js';

// Shared plumbing between routes/media.ts (provider-generic) and
// routes/immich.ts (legacy Immich-only compat — its /api/immich/assets/...
// URL shape is stored in existing posts and generated by pre-built mobile
// clients, see the comment atop that file). Both routes' public contracts
// (paths, params, response shapes, status codes, error keys) must stay
// exactly as they are; these helpers are parameterized (provider resolution,
// URL prefix, fail-soft vs fail-hard on a source error, which response
// fields are included) rather than merged into one behavior. Where a piece
// can't be parameterized without changing either route's contract (e.g.
// media.ts's ?personId= filter, which immich.ts has no equivalent of), it's
// left unshared in the route file instead.

type TFn = (key: string) => string;

// Every media/immich provider call that fails throws MediaProviderError;
// every route maps it to the same translated status/body. Anything else
// rethrows to the global error handler, same as an unguarded call would.
export function sendMediaProviderErrorResponse(err: unknown, reply: FastifyReply, t: TFn) {
  if (err instanceof MediaProviderError) {
    return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
  }
  throw err;
}

// media.ts queries every linked album regardless of provider; immich.ts
// (providerFilter: 'immich') only its own — this mirrors each route's
// original prisma query.
export async function findGroupAlbumLinks(groupId: string, providerFilter?: string): Promise<MediaAlbumLink[]> {
  return prisma.mediaAlbumLink.findMany({
    where: providerFilter ? { groupId, provider: providerFilter } : { groupId },
    orderBy: { createdAt: 'desc' },
  });
}

interface AlbumListRow {
  linkId: string;
  provider?: string;
  albumName: string;
  assetCount: number;
}

// media.ts is fail-soft per album (a source that's down reports assetCount 0
// rather than sinking the whole list); immich.ts is fail-hard (the first
// failing album fails the whole request) — a real, preexisting difference
// between the two routes that this preserves rather than unifies. The two
// also differ in whether provider resolution can ever come back empty
// (media.ts's registry lookup can, for an unregistered/unknown provider
// string; immich.ts's hardcoded provider can't) and whether the response
// carries a `provider` field (media.ts does; immich.ts doesn't, for
// backward compatibility with existing clients).
export async function respondWithAlbumList(
  reply: FastifyReply,
  t: TFn,
  links: MediaAlbumLink[],
  opts: {
    resolveProvider: (link: MediaAlbumLink) => MediaProvider | undefined;
    failSoft: boolean;
    includeProviderField: boolean;
  }
) {
  try {
    return await Promise.all(
      links.map(async (link) => {
        const provider = opts.resolveProvider(link);
        let assetCount = 0;
        if (provider) {
          try {
            assetCount = (await provider.getAlbumInfo(link.externalAlbumId))?.assetCount ?? 0;
          } catch (err) {
            if (!(err instanceof MediaProviderError) || !opts.failSoft) throw err;
          }
        }
        const row: AlbumListRow = { linkId: link.id, albumName: link.albumName, assetCount };
        if (opts.includeProviderField) row.provider = link.provider;
        return row;
      })
    );
  } catch (err) {
    return sendMediaProviderErrorResponse(err, reply, t);
  }
}

// Link lookup shared by the asset-list and asset-stream routes. immich.ts
// passes providerFilter: 'immich' so a link belonging to any other provider
// is treated as not-found right here — matching its original combined
// `!link || link.provider !== 'immich'` check, which ran *before* the group
// membership check. media.ts omits providerFilter (any provider's link is a
// valid lookup) and instead resolves/validates the provider separately,
// *after* the membership check — see resolveProviderOr404 below — matching
// its original ordering. That ordering difference is intentional and
// preexisting: don't collapse the two checks into one shared step.
export async function findAlbumLinkOrNotFound(
  linkId: string,
  opts: { providerFilter?: string; notFoundErrorKey: string }
): Promise<{ ok: true; link: MediaAlbumLink } | { ok: false; status: 404; errorKey: string }> {
  const link = await prisma.mediaAlbumLink.findUnique({ where: { id: linkId } });
  if (!link || (opts.providerFilter && link.provider !== opts.providerFilter)) {
    return { ok: false, status: 404, errorKey: opts.notFoundErrorKey };
  }
  return { ok: true, link };
}

// Only meaningful for media.ts, where the provider is looked up by id and
// can come back empty; for immich.ts, callers pass a resolver that always
// returns immichProvider (provider validity was already established by
// findAlbumLinkOrNotFound's providerFilter), so this never 404s there.
export function resolveProviderOr404(
  link: MediaAlbumLink,
  opts: { resolveProvider: (link: MediaAlbumLink) => MediaProvider | undefined; notFoundErrorKey: string }
): { ok: true; provider: MediaProvider } | { ok: false; status: 404; errorKey: string } {
  const provider = opts.resolveProvider(link);
  if (!provider) return { ok: false, status: 404, errorKey: opts.notFoundErrorKey };
  return { ok: true, provider };
}

interface AssetListItem {
  assetId: string;
  type: MediaAssetSummary['type'];
  width: number | null;
  height: number | null;
  thumbnailUrl: string;
  previewUrl: string;
  originalUrl: string;
}

export function assetToListItem(link: { id: string }, asset: MediaAssetSummary, urlPrefix: string): AssetListItem {
  return {
    assetId: asset.id,
    type: asset.type,
    width: asset.width,
    height: asset.height,
    thumbnailUrl: `${urlPrefix}/${link.id}/${asset.id}/thumbnail.jpg`,
    previewUrl: `${urlPrefix}/${link.id}/${asset.id}/preview.jpg`,
    originalUrl: `${urlPrefix}/${link.id}/${asset.id}/original.${asset.originalExt}`,
  };
}

// Shared list + map + error-translate for the asset-list routes. media.ts's
// ?personId= filter has no immich.ts equivalent, so it's resolved by the
// caller and passed in as filterAssetIds rather than living in here.
export async function listAndMapAlbumAssets(
  provider: MediaProvider,
  link: MediaAlbumLink,
  urlPrefix: string,
  reply: FastifyReply,
  t: TFn,
  filterAssetIds?: Set<string> | null
) {
  try {
    const assets = await provider.listAlbumAssets(link.externalAlbumId);
    const filtered = filterAssetIds ? assets.filter((asset) => filterAssetIds.has(asset.id)) : assets;
    return filtered.map((asset) => assetToListItem(link, asset, urlPrefix));
  } catch (err) {
    return sendMediaProviderErrorResponse(err, reply, t);
  }
}

// Shared isAssetInAlbum re-check + stream + error-translate for the asset
// proxy route (`GET /assets/:linkId/:assetId/:variantExt` in both files).
// streamAsset() itself honors the Range header end-to-end (see the
// MediaProvider contract in ./types.ts) — nothing here alters that.
export async function authorizeAndStreamAsset(
  provider: MediaProvider,
  link: MediaAlbumLink,
  assetId: string,
  variant: MediaAssetVariant,
  reply: FastifyReply,
  range: string | undefined,
  notFoundErrorKey: string,
  t: TFn
) {
  try {
    // The linkId->groupId check the caller already did only proves the
    // requester belongs to the group this album is linked to — it doesn't
    // prove the requested asset is actually in that album. Providers with
    // source-wide credentials/roots must re-check membership here too;
    // otherwise a member who learns an asset id from elsewhere could read
    // assets never linked to Famlin.
    if (!(await provider.isAssetInAlbum(link.externalAlbumId, assetId))) {
      return reply.status(404).send({ error: t(notFoundErrorKey) });
    }
    return await provider.streamAsset(link.externalAlbumId, assetId, variant, reply, range);
  } catch (err) {
    return sendMediaProviderErrorResponse(err, reply, t);
  }
}
