// ESLint flat config for the Expo / React Native app.
//
// mobile/ installs independently (see repo root CLAUDE.md), so it carries
// its own eslint + eslint-config-expo devDependencies rather than relying
// on the root workspace's hoisted node_modules. `eslint-config-expo` is the
// lightweight Expo-ecosystem-standard base (typescript-eslint + React +
// react-hooks + platform globals), used here instead of hand-rolling the
// same thing a second time.
import { defineConfig } from 'eslint/config';
import expoConfig from 'eslint-config-expo/flat.js';
import globals from 'globals';

export default defineConfig([
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      'coverage/**',
      '.expo/**',
      '.eas/**',
      // Native projects are regenerated by `expo prebuild` / EAS Build and
      // gitignored (see mobile/ios, mobile/android in the root .gitignore).
      'ios/**',
      'android/**',
    ],
  },
  expoConfig,
  {
    // Scoped to ts/tsx to match where eslint-config-expo registers the
    // @typescript-eslint plugin — an unscoped override here would fail on
    // plain .js config files (babel.config.js, metro.config.js, ...) where
    // that plugin isn't registered.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Root-level CommonJS tooling config (not bundled by Metro), needs
    // Node's globals; jest.setup.js also runs inside Jest's own globals.
    files: ['jest.config.js', 'jest.setup.js', 'babel.config.js', 'metro.config.js'],
    languageOptions: {
      globals: { ...globals.node, ...globals.jest },
    },
  },
  {
    // React Compiler-derived react-hooks rules (bundled by eslint-config-expo
    // via eslint-plugin-react-hooks' "recommended" preset) surface real,
    // pre-existing patterns across many screens (refs read during render,
    // setState-in-effect, one impure Date.now() call, one hook called from a
    // callback). Downgraded to warn rather than editing source here — see
    // https://react.dev/reference/eslint-plugin-react-hooks for follow-up.
    // react-hooks/immutability also false-positives on Reanimated's
    // useSharedValue `.value =` assignment inside worklets (ChatScreen.tsx's
    // swipe-to-reply gesture) — that's a documented, idiomatic Reanimated
    // API, not a mutation bug, and the rule doesn't know about it.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'react-hooks/refs': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/rules-of-hooks': 'warn',
      'react-hooks/immutability': 'warn',
    },
  },
]);
