import { z } from 'zod';
import { SUPPORTED_LANGUAGES } from './i18n/index.js';

// Matches exactly what routes/uploads.ts writes: /uploads/<uuid>.<allowed-ext>.
// Rejects arbitrary external URLs so a post/comment can't point at a
// tracking pixel or another group's asset path.
const UPLOAD_PATH_REGEX =
  /^\/uploads\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|jpeg|png|gif|webp|heic|heif|mp4|mov|m4v|webm)$/;
const uploadPathSchema = z.string().regex(UPLOAD_PATH_REGEX, 'Must be an uploaded asset path');

// Matches exactly what routes/immich.ts's legacy proxy route serves:
// /api/immich/assets/<MediaAlbumLink cuid>/<Immich asset uuid>/<variant>.<ext>.
// Unlike an upload path, the extension here reflects the real bytes each
// variant streams: `thumbnail`/`preview` always come back as a JPEG (Immich's
// thumbnail endpoint never returns video), so only `original` can be `.mp4`.
// Kept (alongside the generic media shape below) because these URLs are
// stored in existing posts and still generated by pre-built mobile clients.
const IMMICH_ASSET_PATH_REGEX =
  /^\/api\/immich\/assets\/([a-z0-9]+)\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/(?:(thumbnail|preview)\.jpg|(original)\.(?:jpg|mp4))$/;

// Matches what routes/media.ts's provider-generic proxy route serves:
// /api/media/assets/<MediaAlbumLink cuid>/<provider asset id>/<variant>.<ext>.
// The asset id charset covers both an Immich uuid and the local provider's
// base64url-encoded filenames; which provider serves it is determined by the
// link row, not the URL. Keeping this as strict as the upload path regex
// above is what stops a post/comment from pointing at an arbitrary URL.
const MEDIA_ASSET_PATH_REGEX =
  /^\/api\/media\/assets\/([a-z0-9]+)\/([A-Za-z0-9_-]{1,255})\/(?:(thumbnail|preview)\.jpg|(original)\.(?:jpg|jpeg|png|gif|webp|avif|mp4))$/;

export interface MediaAssetPath {
  linkId: string;
  assetId: string;
  variant: 'thumbnail' | 'preview' | 'original';
}

// Single source of truth for the proxy URL shapes (generic + legacy Immich) —
// used by the zod validator below, by routes/media.ts and routes/immich.ts to
// validate :variantExt, and by routes/posts.ts to extract the embedded link
// id for the cross-group check. Use this instead of re-deriving the shape
// elsewhere in the codebase.
export function parseMediaAssetPath(path: string): MediaAssetPath | null {
  const match = path.match(MEDIA_ASSET_PATH_REGEX) ?? path.match(IMMICH_ASSET_PATH_REGEX);
  if (!match) return null;
  const [, linkId, assetId, thumbOrPreview, original] = match;
  return { linkId, assetId, variant: (thumbOrPreview ?? original) as MediaAssetPath['variant'] };
}

const mediaAssetPathSchema = z
  .string()
  .refine((path) => parseMediaAssetPath(path) !== null, 'Must be a valid media asset path');
const assetPathSchema = z.union([uploadPathSchema, mediaAssetPathSchema]);

export const loginBodySchema = z.object({
  idToken: z.string(),
  inviteToken: z.string().optional(),
});

// Used by the admin UI when the configured OIDC provider requires a client
// secret (e.g. Google) — the browser can't hold the secret, so it hands the
// authorization code to the backend instead of exchanging it itself.
export const oidcExchangeBodySchema = z.object({
  code: z.string(),
  redirectUri: z.string(),
  codeVerifier: z.string().optional(),
  inviteToken: z.string().optional(),
});

// Redeems the one-time code the mobile app receives from the
// famlin://oidc-callback deep link after GET /api/auth/oidc/mobile-callback
// completes a server-mediated (client-secret) login.
export const oidcMobileHandoffBodySchema = z.object({
  code: z.string(),
});

// allowedPostTypes stays a loose string array here — each id is validated
// against the PostTypeHandler registry in routes/admin.ts instead, so the
// admin gets the specific errors.unknownPostType message rather than a
// generic zod validationFailed. Empty array (or omitted on create) = all
// types allowed, same convention as allowedEmails.
const allowedPostTypesSchema = z.array(z.string().min(1).max(30)).max(50);

export const createGroupBodySchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().max(500).optional(),
  allowedPostTypes: allowedPostTypesSchema.optional(),
  chitchatEnabled: z.boolean().optional(),
});

export const groupMemberBodySchema = z.object({
  userId: z.string(),
});

const locationFieldsSchema = z.object({
  latitude: z.number().min(-90).max(90).optional(),
  longitude: z.number().min(-180).max(180).optional(),
  locationName: z.string().max(200).optional(),
});

function requireLatLngTogether(data: { latitude?: number; longitude?: number }) {
  return (data.latitude === undefined) === (data.longitude === undefined);
}

export const createPostBodySchema = z
  .object({
    // Legacy single-group shape — still accepted unchanged so existing
    // clients keep working. `groupIds` (cross-posting: one Post row per
    // target group, see routes/posts.ts) is the newer, general shape; the
    // refine below requires at least one of the two.
    groupId: z.string().optional(),
    groupIds: z.array(z.string()).min(1).max(20).optional(),
    content: z.string().max(5000).optional(),
    // An open string discriminator (was a closed 'UPDATE'|'MILESTONE' enum) —
    // routes/posts.ts looks it up in the PostTypeHandler registry
    // (services/postTypes/registry.ts) and 400s on an unregistered id.
    type: z.string().max(30).default('UPDATE'),
    milestoneTag: z.string().max(50).optional(),
    // Handler-owned, type-specific config (e.g. a poll's options/closesAt) —
    // validated against the matching PostTypeHandler's own typeDataSchema in
    // routes/posts.ts, not here (this schema can't know which shape a given
    // type expects).
    typeData: z.unknown().optional(),
    uploadedAssetUrls: z.array(assetPathSchema).max(20).optional(),
  })
  .merge(locationFieldsSchema)
  .refine(requireLatLngTogether, { message: 'latitude and longitude must be provided together', path: ['latitude'] })
  .refine((data) => !!data.groupId || (data.groupIds && data.groupIds.length > 0), {
    message: 'groupId or groupIds is required',
    path: ['groupId'],
  });

export const createCommentBodySchema = z
  .object({
    // Optional so a comment can be photo/video-only — the refine below still
    // requires at least one of content/attachmentUrl.
    content: z.string().max(2000).optional(),
    parentId: z.string().optional(),
    assetUrl: assetPathSchema.optional(),
    // A photo/video the commenter uploaded specifically for this comment
    // (via POST /api/uploads), distinct from assetUrl above which instead
    // pins the comment to an existing asset already on the post.
    attachmentUrl: uploadPathSchema.optional(),
    // IDs the client resolved from the group member list while typing "@name" —
    // the server only trusts these as a set of candidate ids and still
    // re-validates each one is a current member of the post's group.
    mentionedUserIds: z.array(z.string()).max(20).optional(),
  })
  .refine((data) => !!data.content?.trim() || !!data.attachmentUrl, {
    message: 'content or attachmentUrl is required',
    path: ['content'],
  });

// POST /api/chat/groups/:groupId/messages — mirrors createCommentBodySchema's
// "at least one of content/attachmentUrl" shape (a chat message can be
// photo/video-only too).
export const createChatMessageBodySchema = z
  .object({
    content: z.string().max(2000).optional(),
    attachmentUrl: uploadPathSchema.optional(),
    replyToMessageId: z.string().optional(),
  })
  .refine((data) => !!data.content?.trim() || !!data.attachmentUrl, {
    message: 'content or attachmentUrl is required',
    path: ['content'],
  });

export const reactionTypeSchema = z.enum(['LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'CARE']);

export const reactionBodySchema = z.object({
  type: reactionTypeSchema.default('LIKE'),
});

// POST /api/posts/:postId/interactions — a post-type-specific action (poll
// voting today; RSVPs etc. later). `key`/`value` are opaque here on purpose:
// the matching PostTypeHandler (services/postTypes/registry.ts) is what
// knows what a valid key/value pair looks like for its own type.
export const postInteractionBodySchema = z.object({
  key: z.string().min(1).max(50),
  value: z.unknown().optional(),
});

export const updatePostBodySchema = z
  .object({
    content: z.string().max(5000).optional(),
    milestoneTag: z.string().max(50).optional(),
    latitude: z.number().min(-90).max(90).nullable().optional(),
    longitude: z.number().min(-180).max(180).nullable().optional(),
    locationName: z.string().max(200).nullable().optional(),
    // Present so a cross-posted edit can rewrite a linked-album asset via
    // copyMediaAssetsToUploads (see routes/posts.ts PATCH /:id) — no client
    // sends this on a plain edit today, but it's the same shape as create's.
    uploadedAssetUrls: z.array(assetPathSchema).max(20).optional(),
  })
  .refine((data) => (data.latitude == null) === (data.longitude == null), {
    message: 'latitude and longitude must be provided together',
    path: ['latitude'],
  });

export const updateCommentBodySchema = z.object({
  content: z.string().min(1).max(2000),
});

export const pushTokenBodySchema = z.object({
  token: z.string(),
});

export const createApiTokenBodySchema = z.object({
  name: z.string().min(1).max(100),
  // Omitted = the token never expires (revocable any time); capped at ten
  // years so a typo can't create an effectively-immortal "temporary" token.
  expiresInDays: z.number().int().positive().max(3650).optional(),
});

export const updateNotificationBodySchema = z.object({
  read: z.boolean(),
});

export const notificationPrefsSchema = z.object({
  emailOnNewPost: z.boolean().optional(),
  emailOnNewComment: z.boolean().optional(),
  emailOnNewLike: z.boolean().optional(),
  pushOnNewPost: z.boolean().optional(),
  pushOnNewComment: z.boolean().optional(),
  pushOnNewLike: z.boolean().optional(),
  pushOnChitchat: z.boolean().optional(),
});

// Clients always upload the photo first and pass back the resulting
// /uploads path (see mobile ProfileScreen's pickAvatar flow) — an arbitrary
// external URL here would let a user beacon every group member's client to
// attacker-controlled infrastructure on avatar render. (OIDC-provided profile
// pictures are synced separately in routes/auth.ts and don't go through this
// schema.)
export const updateUserBodySchema = notificationPrefsSchema.extend({
  avatarUrl: uploadPathSchema.optional().nullable(),
});

export const adminUpdateUserBodySchema = notificationPrefsSchema.extend({
  isAdmin: z.boolean().optional(),
});

export const adminUpdateGroupBodySchema = z.object({
  name: z.string().min(1).max(100).optional(),
  description: z.string().max(500).optional().nullable(),
  // Explicit empty array = back to "all types allowed"; omitted = unchanged.
  allowedPostTypes: allowedPostTypesSchema.optional(),
  // Omitted = unchanged (plain boolean, no reset-to-default convention needed
  // like allowedPostTypes' empty-array case).
  chitchatEnabled: z.boolean().optional(),
});

export const passwordLoginBodySchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
  inviteToken: z.string().optional(),
});

export const registerBodySchema = z.object({
  email: z.string().email(),
  name: z.string().min(1).max(100),
  password: z.string().min(8).max(100),
  isAdmin: z.boolean().optional(),
  groupIds: z.array(z.string().min(1)).optional(),
});

export const setupBodySchema = z.object({
  email: z.string().email(),
  name: z.string().min(1).max(100),
  password: z.string().min(8).max(100),
});

export const changePasswordBodySchema = z.object({
  currentPassword: z.string().min(1),
  newPassword: z.string().min(8).max(100),
});

export const resetPasswordBodySchema = z.object({
  newPassword: z.string().min(8).max(100),
});

export const updateServerSettingsBodySchema = z.object({
  defaultLanguage: z.enum(SUPPORTED_LANGUAGES).optional(),
  appStoreUrl: z.union([z.literal(''), z.string().url()]).optional(),
  playStoreUrl: z.union([z.literal(''), z.string().url()]).optional(),
  allowedEmails: z.array(z.string().email()).optional(),
  oidcName: z.string().max(50).optional(),
  oidcIssuer: z.string().optional(),
  oidcClientId: z.string().optional(),
  oidcClientSecret: z.string().optional(),
  oidcScopes: z.string().optional(),
  smtpHost: z.string().optional(),
  smtpPort: z.number().optional(),
  smtpUser: z.string().optional(),
  smtpPass: z.string().optional(),
  // Allows both a bare address and the "Name <email>" display-name format.
  smtpFrom: z.string().max(200).optional(),
  pushNotificationsEnabled: z.boolean().optional(),
  emailNotificationsEnabled: z.boolean().optional(),
  immichServerUrl: z.union([z.literal(''), z.string().url()]).optional(),
  immichApiKey: z.string().optional(),
  // Absolute container-side path for the local-folder media source; empty
  // string = not configured.
  localMediaPath: z.union([z.literal(''), z.string().regex(/^\//, 'Must be an absolute path').max(500)]).optional(),
});

export const testImmichConnectionBodySchema = z.object({
  serverUrl: z.string().url(),
  apiKey: z.string().min(1),
});

export const linkMediaAlbumBodySchema = z.object({
  // Must be a registered provider id (services/media/registry.ts); the route
  // additionally checks provider.isValidAlbumId() before creating the link.
  provider: z.enum(['immich', 'local']),
  externalAlbumId: z.string().min(1).max(300),
  albumName: z.string().min(1).max(200),
});

export const testLocalMediaBodySchema = z.object({
  rootPath: z.string().regex(/^\//, 'Must be an absolute path').max(500),
});

export const newAssetModeSchema = z.enum(['OFF', 'MANUAL', 'AUTO']);

export const updateMediaAlbumLinkBodySchema = z.object({
  newAssetMode: newAssetModeSchema,
});

// provider isn't restricted to the registered provider enum here (unlike
// linkMediaAlbumBodySchema) because a person mapping can outlive a provider
// being removed from the registry — the row itself is harmless to keep.
export const createMediaPersonLinkBodySchema = z.object({
  provider: z.string().min(1).max(50),
  externalPersonId: z.string().min(1).max(300),
  label: z.string().min(1).max(100),
  userId: z.string().optional(),
});

export const createInviteBodySchema = z.object({
  email: z.string().email().optional(),
  expiresInDays: z.number().int().positive().max(365).optional(),
});

export const paginationQuerySchema = z.object({
  cursor: z.string().optional(),
  take: z.coerce.number().int().min(1).max(100).default(30),
});

export const searchPostsQuerySchema = paginationQuerySchema.extend({
  groupId: z.string(),
  q: z.string().trim().min(1).max(200),
});

// GET /api/media/groups/:groupId/photos — bigger default/max page than the
// generic paginationQuerySchema above (a photo grid wants more tiles per
// page than the feed's 30/100), and its cursor is an opaque base64 keyset
// token over the in-memory-merged (takenAt, id) ordering rather than a
// Prisma row id — see services/media/photoTimeline.ts's encodeCursor.
export const photoTimelineQuerySchema = z.object({
  cursor: z.string().optional(),
  take: z.coerce.number().int().min(1).max(200).default(60),
  personId: z.string().optional(),
});

export const inviteRegisterBodySchema = z.object({
  name: z.string().min(1).max(100),
  email: z.string().email().optional(),
  password: z.string().min(8).max(100),
});
