import { FastifyInstance } from 'fastify';
import { prisma } from '../db.js';
import { authenticateMediaRequest } from '../plugins/auth.js';
import { isGroupMember } from '../services/groups.js';
import { immichProvider } from '../services/media/immich.js';
import { mediaErrorKey, mediaErrorStatus, MediaProviderError } from '../services/media/registry.js';
import { parseMediaAssetPath } from '../types.js';
import { getT } from '../i18n/index.js';

// Legacy Immich-only member routes, kept for compatibility: the asset URL
// shape (/api/immich/assets/...) is stored in existing posts'
// uploadedAssetUrls and still generated by pre-built mobile clients. New
// clients should use the provider-generic routes/media.ts endpoints instead —
// these delegate to the same immichProvider and stay Immich-scoped
// (provider: 'immich' filter below).
export default async function immichRoutes(fastify: FastifyInstance) {
  fastify.get('/groups/:groupId/albums', { preHandler: [fastify.authenticate] }, async (request, reply) => {
    const t = getT(request);
    const { groupId } = request.params as { groupId: string };

    if (!(await isGroupMember(groupId, request.user!.id))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    const links = await prisma.mediaAlbumLink.findMany({
      where: { groupId, provider: 'immich' },
      orderBy: { createdAt: 'desc' },
    });
    if (links.length === 0) return [];

    try {
      // Per-link lookup rather than the full-instance catalog — a group
      // typically has one or two linked albums, so this doesn't scale with
      // the size of the whole Immich library.
      return await Promise.all(
        links.map(async (link) => ({
          linkId: link.id,
          albumName: link.albumName,
          assetCount: (await immichProvider.getAlbumInfo(link.externalAlbumId))?.assetCount ?? 0,
        }))
      );
    } catch (err) {
      if (err instanceof MediaProviderError) {
        return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
      }
      throw err;
    }
  });

  fastify.get('/albums/:linkId/assets', { preHandler: [fastify.authenticate] }, async (request, reply) => {
    const t = getT(request);
    const { linkId } = request.params as { linkId: string };

    const link = await prisma.mediaAlbumLink.findUnique({ where: { id: linkId } });
    if (!link || link.provider !== 'immich') {
      return reply.status(404).send({ error: t('errors.immichAlbumLinkNotFound') });
    }

    if (!(await isGroupMember(link.groupId, request.user!.id))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    try {
      const assets = await immichProvider.listAlbumAssets(link.externalAlbumId);
      return assets.map((asset) => ({
        assetId: asset.id,
        type: asset.type,
        width: asset.width,
        height: asset.height,
        thumbnailUrl: `/api/immich/assets/${link.id}/${asset.id}/thumbnail.jpg`,
        previewUrl: `/api/immich/assets/${link.id}/${asset.id}/preview.jpg`,
        originalUrl: `/api/immich/assets/${link.id}/${asset.id}/original.${asset.originalExt}`,
      }));
    } catch (err) {
      if (err instanceof MediaProviderError) {
        return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
      }
      throw err;
    }
  });

  // No fastify.authenticate here: this is loaded as an <Image>/<Video> `uri`,
  // which can't send custom headers, so it must accept the same dual auth
  // (session token or media token) that gates /uploads/* — see
  // authenticateMediaRequest in plugins/auth.ts.
  fastify.get('/assets/:linkId/:assetId/:variantExt', async (request, reply) => {
    const t = getT(request);
    const userId = await authenticateMediaRequest(request);
    if (!userId) return reply.status(401).send({ error: t('errors.unauthorized') });

    const { linkId, assetId, variantExt } = request.params as { linkId: string; assetId: string; variantExt: string };
    const parsed = parseMediaAssetPath(`/api/immich/assets/${linkId}/${assetId}/${variantExt}`);
    if (!parsed) {
      return reply.status(404).send({ error: t('errors.immichAlbumLinkNotFound') });
    }

    const link = await prisma.mediaAlbumLink.findUnique({ where: { id: linkId } });
    if (!link || link.provider !== 'immich') {
      return reply.status(404).send({ error: t('errors.immichAlbumLinkNotFound') });
    }

    if (!(await isGroupMember(link.groupId, userId))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    try {
      // The linkId->groupId check above only proves the requester belongs to
      // the group this album is linked to — it doesn't prove the requested
      // asset is actually in that album. Since the server-level API key can
      // read any asset on the Immich instance, re-check membership here too;
      // otherwise a member who learns an asset id from elsewhere (e.g.
      // another group's post) could read assets never linked to Famlin.
      if (!(await immichProvider.isAssetInAlbum(link.externalAlbumId, assetId))) {
        return reply.status(404).send({ error: t('errors.immichAlbumLinkNotFound') });
      }

      return await immichProvider.streamAsset(link.externalAlbumId, assetId, parsed.variant, reply, request.headers.range);
    } catch (err) {
      if (err instanceof MediaProviderError) {
        return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
      }
      throw err;
    }
  });
}
