import { FastifyInstance } from 'fastify';
import { prisma } from '../db.js';
import { authenticateMediaRequest } from '../plugins/auth.js';
import { isGroupMember } from '../services/groups.js';
import { getMediaProvider, mediaErrorKey, mediaErrorStatus, MediaProviderError } from '../services/media/registry.js';
import { parseMediaAssetPath } from '../types.js';
import { getT } from '../i18n/index.js';

// Member-facing, provider-generic media endpoints — read/proxy-only, same
// spirit as routes/groups.ts; linking albums to a group is an admin mutation
// in routes/admin.ts. The legacy Immich-only equivalents in routes/immich.ts
// stay because their URL shapes are stored in existing posts and generated by
// pre-built mobile clients; new clients should use these instead.
export default async function mediaRoutes(fastify: FastifyInstance) {
  fastify.get('/groups/:groupId/albums', { preHandler: [fastify.authenticate] }, async (request, reply) => {
    const t = getT(request);
    const { groupId } = request.params as { groupId: string };

    if (!(await isGroupMember(groupId, request.user!.id))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    const links = await prisma.mediaAlbumLink.findMany({ where: { groupId }, orderBy: { createdAt: 'desc' } });
    if (links.length === 0) return [];

    // Per-link lookup rather than each provider's full catalog — a group
    // typically has one or two linked albums. A link whose provider is
    // failing reports assetCount 0 rather than sinking the whole list, so one
    // unreachable source can't hide the others' albums.
    return Promise.all(
      links.map(async (link) => {
        const provider = getMediaProvider(link.provider);
        let assetCount = 0;
        if (provider) {
          try {
            assetCount = (await provider.getAlbumInfo(link.externalAlbumId))?.assetCount ?? 0;
          } catch (err) {
            if (!(err instanceof MediaProviderError)) throw err;
          }
        }
        return { linkId: link.id, provider: link.provider, albumName: link.albumName, assetCount };
      })
    );
  });

  fastify.get('/albums/:linkId/assets', { preHandler: [fastify.authenticate] }, async (request, reply) => {
    const t = getT(request);
    const { linkId } = request.params as { linkId: string };
    // externalPersonId (not the MediaPersonLink row id) — filters the album
    // down to one recognized person via set intersection.
    const { personId } = request.query as { personId?: string };

    const link = await prisma.mediaAlbumLink.findUnique({ where: { id: linkId } });
    if (!link) return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });

    if (!(await isGroupMember(link.groupId, request.user!.id))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    const provider = getMediaProvider(link.provider);
    if (!provider) return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });

    let personAssetIds: Set<string> | null = null;
    if (personId) {
      // Only a mapped person can be filtered on — this also stops a client
      // from probing arbitrary provider-side person ids that were never
      // deliberately exposed to families via the admin mapping UI.
      const personLink = await prisma.mediaPersonLink.findUnique({
        where: { provider_externalPersonId: { provider: link.provider, externalPersonId: personId } },
      });
      if (!personLink) return reply.status(404).send({ error: t('errors.mediaPersonLinkNotFound') });
      if (!provider.getPersonAssetIds) {
        return reply.status(400).send({ error: t('errors.mediaProviderLacksPersonFilter') });
      }
      try {
        personAssetIds = await provider.getPersonAssetIds(personId);
      } catch (err) {
        if (err instanceof MediaProviderError) {
          return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
        }
        throw err;
      }
    }

    try {
      const assets = await provider.listAlbumAssets(link.externalAlbumId);
      const filtered = personAssetIds ? assets.filter((asset) => personAssetIds!.has(asset.id)) : assets;
      return filtered.map((asset) => ({
        assetId: asset.id,
        type: asset.type,
        width: asset.width,
        height: asset.height,
        thumbnailUrl: `/api/media/assets/${link.id}/${asset.id}/thumbnail.jpg`,
        previewUrl: `/api/media/assets/${link.id}/${asset.id}/preview.jpg`,
        originalUrl: `/api/media/assets/${link.id}/${asset.id}/original.${asset.originalExt}`,
      }));
    } catch (err) {
      if (err instanceof MediaProviderError) {
        return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
      }
      throw err;
    }
  });

  // Mapped people for every media source a group has at least one linked
  // album on — the member-facing "filter by person" picker's catalog. Empty
  // array (not an error) when the group has no linked albums or none of its
  // providers have any mapped people.
  fastify.get('/people', { preHandler: [fastify.authenticate] }, async (request, reply) => {
    const t = getT(request);
    const { groupId } = request.query as { groupId?: string };
    if (!groupId) return reply.status(400).send({ error: t('errors.groupIdRequired') });

    if (!(await isGroupMember(groupId, request.user!.id))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    const links = await prisma.mediaAlbumLink.findMany({ where: { groupId }, select: { provider: true } });
    const providerIds = [...new Set(links.map((l) => l.provider))];
    if (providerIds.length === 0) return [];

    const people = await prisma.mediaPersonLink.findMany({ where: { provider: { in: providerIds } } });
    return people.map((p) => ({
      id: p.externalPersonId,
      provider: p.provider,
      label: p.label,
      userId: p.userId,
    }));
  });

  // No fastify.authenticate here: this is loaded as an <Image>/<Video> `uri`,
  // which can't send custom headers, so it must accept the same dual auth
  // (session token or media token) that gates /uploads/* — see
  // authenticateMediaRequest in plugins/auth.ts.
  fastify.get('/assets/:linkId/:assetId/:variantExt', async (request, reply) => {
    const t = getT(request);
    const userId = await authenticateMediaRequest(request);
    if (!userId) return reply.status(401).send({ error: t('errors.unauthorized') });

    const { linkId, assetId, variantExt } = request.params as { linkId: string; assetId: string; variantExt: string };
    const parsed = parseMediaAssetPath(`/api/media/assets/${linkId}/${assetId}/${variantExt}`);
    if (!parsed) {
      return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });
    }

    const link = await prisma.mediaAlbumLink.findUnique({ where: { id: linkId } });
    if (!link) return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });

    if (!(await isGroupMember(link.groupId, userId))) {
      return reply.status(403).send({ error: t('errors.notGroupMember') });
    }

    const provider = getMediaProvider(link.provider);
    if (!provider) return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });

    try {
      // The linkId->groupId check above only proves the requester belongs to
      // the group this album is linked to — it doesn't prove the requested
      // asset is actually in that album. Providers with source-wide
      // credentials (Immich's server-level API key) or a source-wide root
      // (the local folder) must re-check membership here too; otherwise a
      // member who learns an asset id from elsewhere could read assets never
      // linked to Famlin.
      if (!(await provider.isAssetInAlbum(link.externalAlbumId, assetId))) {
        return reply.status(404).send({ error: t('errors.mediaAlbumLinkNotFound') });
      }

      return await provider.streamAsset(link.externalAlbumId, assetId, parsed.variant, reply, request.headers.range);
    } catch (err) {
      if (err instanceof MediaProviderError) {
        return reply.status(mediaErrorStatus(err)).send({ error: t(mediaErrorKey(err)) });
      }
      throw err;
    }
  });
}
