import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// Generated by `npm run gen-api-docs` from openapi/famlin.yaml — regenerate
// after editing the spec; don't edit the api-reference/ output by hand.
import apiReferenceSidebar from './developers/api-reference/sidebar';

const sidebars: SidebarsConfig = {
  developersSidebar: [
    'quick-start',
    'architecture',
    'api',
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      items: apiReferenceSidebar,
    },
    'contributing',
    'project-brief',
  ],
};

export default sidebars;
